### ISSUE TITLE
Speedup inferrence time. 

### ISSUE THREAD

**Issue by rohaantahir** [cliffordkleinsr/DE-SRFREN#3]
HI @cliffordkleinsr very nice work. I would be very much happy and interested in speedup the inferrence time. Are you working on it ?

**Comment by cliffordkleinsr** [comment]
Yes the new code has sped up the inference time effectively halving the frame parsing, will share the colab code to run the inference publicly, where you can run the inference

**Comment by rohaantahir** [comment]
@cliffordkleinsr sure, looking forward to it. thanks

**Comment by cliffordkleinsr** [comment]
Have you tested out the code?

**Comment by rohaantahir** [comment]
Yeah I have checked in my local. but will love to see your colab version.

**Comment by cliffordkleinsr** [comment]
will do

**Comment by cliffordkleinsr** [comment]
The code now has both terminal and colab implementations on the repo, give it a try and let me know how it goes
