### ISSUE TITLE
Number of processes must be at least 1

### ISSUE THREAD

**Issue by JuvenileLocksmith** [cliffordkleinsr/DE-SRFREN#5]
_(desfren) C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2>_**python inference.py -i  C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2>C:\Users\pompous_pigeon\Videos\bob_final_2.mp4 --ffmpeg_bin ffmpeg/bin/ffmpeg.exe --ffprobe_bin ffmpeg/bin/ffprobe.exe --face_enhance --suffix outx2**
_C:\Program Files\Python310\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2\inference.py", line 232, in <module>
    main()
  File "C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2\inference.py", line 227, in main
    run(args)
  File "C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2\inference.py", line 155, in run
    pool = ctx.Pool(num_process)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")_
**ValueError: Number of processes must be at least 1**

**Comment by cliffordkleinsr** [comment]
The default num_process is set to one but what you could try is adding the following flag `--num_process_per_gpu 1` to force it to use 1 sub-process.

Therefore your command would be:
```py
python inference.py -i C:\Users\pompous_pigeon\Desktop\DE-SRFREN\v0.0.2>C:\Users\pompous_pigeon\Videos\bob_final_2.mp4 --ffmpeg_bin ffmpeg/bin/ffmpeg.exe --ffprobe_bin ffmpeg/bin/ffprobe.exe --face_enhance --num_process_per_gpu 1 --suffix outx2
```
Additionally consider adding  `ffmpeg` to your environment variables so it can run automatically without the additional flags:
`--ffmpeg_bin ffmpeg/bin/ffmpeg.exe --ffprobe_bin ffmpeg/bin/ffprobe.exe`

**Comment by cliffordkleinsr** [comment]
closed due to inactivity
